# Generated by Django 4.1.2 on 2022-10-27 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_category_slug_remove_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, verbose_name='0=default 1=Hidden'),
        ),
        migrations.AlterField(
            model_name='category',
            name='trending',
            field=models.BooleanField(default=False, verbose_name='0=default 1=Trending'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, verbose_name='0=default 1=Hidden'),
        ),
        migrations.AlterField(
            model_name='product',
            name='trending',
            field=models.BooleanField(default=False, verbose_name='0=default 1=Trending'),
        ),
    ]
