# Generated by Django 4.1.2 on 2022-11-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_cart_size_orderitem_size_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('XLL', 'XLL'), ('XLLL', 'XLLL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Out for Shipping', 'Out for Shipping')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('XLL', 'XLL'), ('XLLL', 'XLLL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('XLL', 'XLL'), ('XLLL', 'XLLL'), ('XL', 'XL'), ('L', 'L'), ('M', 'M')], default='M', max_length=50),
        ),
    ]
