# Generated by Django 4.1.2 on 2022-11-15 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_size_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='size',
            field=models.CharField(choices=[('XLLL', 'XLLL'), ('L', 'L'), ('XL', 'XL'), ('M', 'M'), ('XLL', 'XLL'), ('S', 'S')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Out for Shipping', 'Out for Shipping'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=150),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='size',
            field=models.CharField(choices=[('XLLL', 'XLLL'), ('L', 'L'), ('XL', 'XL'), ('M', 'M'), ('XLL', 'XLL'), ('S', 'S')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('XLLL', 'XLLL'), ('L', 'L'), ('XL', 'XL'), ('M', 'M'), ('XLL', 'XLL'), ('S', 'S')], default='M', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/images/users.png', null=True, upload_to='static/users'),
        ),
    ]
